language: ruby
rvm:
  - 2.0.0
  - 2.1.2
  - 2.2.0
gemfile:
  - gemfiles/Gemfile.rails-3.X
  - gemfiles/Gemfile.rails-4.0
env:
  - PA_ORM=mongoid
  - PA_ORM=mongo_mapper
services:
  - mongodb
email:
  recipients:
    - piotrek@okonski.org
    - jakub@okonski.org
  on_success: change
  on_failure: always
