language: ruby
rvm:
  - 1.9.3
  - 2.0.0
include:
  - gemfile: gemfiles/Gemfile.rails-3.X
    env: NOCOV=true PA_ORM=active_record
env:
  - NOCOV=true PA_ORM=active_record
  - NOCOV=true PA_ORM=mongoid
  - NOCOV=true PA_ORM=mongoid PA_PURGE=true
  - NOCOV=true PA_ORM=mongo_mapper
services:
  - mongodb
email:
  recipients:
    - piotrek@okonski.org
    - jakub@okonski.org
  on_success: change
  on_failure: always
